### ISSUE TITLE
Can I run a task at say 100ms instead of parts of a minute

### ISSUE THREAD

**Issue by Skyhikeeper** [thomasgalliker/NCrontab.Scheduler#14]
Hi 

Is it possible to execute a method every 100ms using the scheduler?

Terence

**Comment by Skyhikeeper** [comment]
because using the cron times it only allows to minutes

**Comment by thomasgalliker** [comment]
Yes, crontab only allows to have minute precision. Since everything is designed to work with cron schedules, `Scheduler` can for now not support intervals lower than 1 minute.
I think you should use Threading Timers to deal with such short intervals. Pretty sure you find something on the internet.
If I ever invest something into extending this library for intervals < 1min, I'll let you know.

**Comment by thomasgalliker** [comment]
@Skyhikeeper I did some more research and found out, that you can configure NCrontab to parse seconds precision. Not sure if this helps you. I also had some discussions among peer developers and they agreed, that for100ms-recurring events you should better use a System.Threading.Timer. If I find some time, I will provide an IScheduler implementation which supports both, cron expressions and TimeSpans.

https://github.com/thomasgalliker/NCrontab.Scheduler/pull/18/commits/3c50b85e4a3afe5dbed49bdc85841146fbba2c2f
